[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true


# Website
[tasks.install_frontend]
command = "yarn"
args = ["install"]
workspace = false
cwd = "./cloud_manager_frontend/"

[tasks.build_frontend]
command = "yarn"
args = ["build"]
workspace = false
cwd = "./cloud_manager_frontend/"
dependencies = [
  "install_frontend"
]

## Rust

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = [
  "format"
]

[tasks.rebuild]
dependencies = [
  "clean",
  "build"
]

[tasks.ci]
dependencies = [
  "rebuild"
# "test"
]
