[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true


# Website

## Rust

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = [
  "format"
]

[tasks.rebuild]
dependencies = [
  "clean",
  "build"
]

[tasks.ci]
dependencies = [
  "rebuild"
# "test"
]
