[package]
name = "shared_model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k8s-openapi = { version = "0.21.1", features = ["v1_29"] }
serde = { version = "1.0.197", features = ["derive"] }
