replicaCount: 1

name_prefix: hermes

image:
  repository: hermes_device
  tag: 0.0.1
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

configMap:
  name: hermes-config-map

rabbitmq:
  enabled: true
  clustering:
    enabled: false
  persistence:
    enabled: false
  fullNameOverride: hermes-rabbitmq
